### ISSUE TITLE
Add a "Why" section to the readme

### ISSUE THREAD

**Issue by johannesjo** [kgabis/ape#1]
İmpressive! But I'm asking myself the question, why should I use this language.

**Comment by apankrat** [comment]
I doubt it's possible to answer that until it sees some adoption and it becomes obvious how people are actually using it. A better option would be just to copy-paste the [background blurb](https://news.ycombinator.com/item?id=22732841) from the Krzysztof's HN post.

**Comment by crash83k** [comment]
I'm curious, too. It looks like a mix of a few functional languages with no typing or OO. Totally functional. But I don't see where it's useful unless there's something I'm missing.

**Comment by xyproto** [comment]
I think this looks useful for game development, web servers or embedded. 

Sometimes, a clearer and less error prone language is useful.

Also, plugins.

**Comment by kgabis** [comment]
Reading https://news.ycombinator.com/item?id=22732841 should give you some context.
Basically if you need some sort of logic in your application you might want to make it configurable at runtime or have it stored in a separate script you load at startup. Ape let's you easily do that since it's very easy to embed in your project and the language is familiar enough so most users won't have to read a book to know how to program in it. Obviously Lua serves a similar purpose and is a much more mature language but it's not very easy to start writing code in.
